login: &login
  username: root
  password: 
  adapter:  mysql
  host:     localhost
  encoding: utf8
  reconnect: false
  pool: 5
  socket: /tmp/mysql.sock

development:
  <<: *login
  database: seed_development

test:
  database: seed_test
  <<: *login

production:
  database: seed_production
  <<: *login
  # username: root
  # password: 
  # adapter:  mysql
  # host:     localhost