development:
  # Sqlite3 Settings
  adapter: sqlite3
  database: db/development.sqlite3
  timeout: 5000

test:
  # Sqlite3 Settings
  adapter: sqlite3
  database: db/test.sqlite3
  timeout: 5000

production:
  # Sqlite3 Settings
  adapter: sqlite3
  database: db/production.sqlite3
  timeout: 5000
